# Workflow cho pre-release (alpha, beta, rc)
name: Pre-release

on:
    push:
        branches: [develop]

jobs:
    prerelease:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: '8.0.x'

            - name: Generate pre-release version
              id: version
              run: |
                  BASE_VERSION=$(grep -o '<Version>[^<]*' src/FSRS.Core/FSRS.Core.csproj | grep -o '[0-9]*\.[0-9]*\.[0-9]*')
                  PRERELEASE_VERSION="$BASE_VERSION-alpha.$(date +'%Y%m%d%H%M%S')"
                  echo "VERSION=$PRERELEASE_VERSION" >> $GITHUB_OUTPUT

            - name: Update version
              run: |
                  sed -i "s|<Version>.*</Version>|<Version>${{ steps.version.outputs.VERSION }}</Version>|" src/FSRS.Core/FSRS.Core.csproj

            - name: Build and Pack
              run: |
                  dotnet restore
                  dotnet build --configuration Release
                  dotnet pack --configuration Release --output ./nupkg

            - name: Publish pre-release
              run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source nuget.org --skip-duplicate
